
services:
  app:
    image: guilhermeuptotask/mercado-livre-scraper
    working_dir: /app
    ports:
      - 0.0.0.0:8000:8000
    volumes:
      - mercado_livre_products:/app/dbs
    

volumes:

  mercado_livre_products: